export interface MerchantCategory {
  category: string;
  keywords: string[];
}

export const MERCHANT_CATEGORY_MAP: Record<string, string> = {
  // Food
  zomato: 'Food & Dining',
  swiggy: 'Food & Dining',
  mcdonalds: 'Food & Dining',
  mcdonald: 'Food & Dining',
  dominos: 'Food & Dining',
  'dominos pizza': 'Food & Dining',
  kfc: 'Food & Dining',
  burgerking: 'Food & Dining',
  'burger king': 'Food & Dining',
  starbucks: 'Food & Dining',
  subway: 'Food & Dining',
  pizzahut: 'Food & Dining',
  'pizza hut': 'Food & Dining',
  domino: 'Food & Dining',
  'la pinoz': 'Food & Dining',
  wowmomo: 'Food & Dining',
  'barbeque nation': 'Food & Dining',
  burger: 'Food & Dining',
  'cafe coffee day': 'Food & Dining',
  ccd: 'Food & Dining',
  chai: 'Food & Dining',
  restaurant: 'Food & Dining',
  dhaba: 'Food & Dining',
  biryani: 'Food & Dining',
  bikaner: 'Food & Dining',
  haldiram: 'Food & Dining',
  swad: 'Food & Dining',
  'baskin robbins': 'Food & Dining',
  'ice cream': 'Food & Dining',
  fssai: 'Food & Dining',

  // Travel
  uber: 'Travel & Transport',
  ola: 'Travel & Transport',
  rapido: 'Travel & Transport',
  irctc: 'Travel & Transport',
  'irctc railway': 'Travel & Transport',
  metro: 'Travel & Transport',
  meru: 'Travel & Transport',
  savaari: 'Travel & Transport',
  redbus: 'Travel & Transport',
  makemytrip: 'Travel & Transport',
  mmt: 'Travel & Transport',
  goibibo: 'Travel & Transport',
  cleartrip: 'Travel & Transport',
  yatra: 'Travel & Transport',
  'ola cabs': 'Travel & Transport',
  'uber india': 'Travel & Transport',
  blusmart: 'Travel & Transport',
  'indigo airlines': 'Travel & Transport',
  'air india': 'Travel & Transport',
  spicejet: 'Travel & Transport',
  vistara: 'Travel & Transport',
  goair: 'Travel & Transport',
  akasa: 'Travel & Transport',
  taxi: 'Travel & Transport',
  cab: 'Travel & Transport',
  parking: 'Travel & Transport',
  toll: 'Travel & Transport',
  fastag: 'Travel & Transport',
  pnr: 'Travel & Transport',

  // Shopping
  amazon: 'Shopping',
  flipkart: 'Shopping',
  myntra: 'Shopping',
  meesho: 'Shopping',
  ajio: 'Shopping',
  nykaa: 'Shopping',
  snapdeal: 'Shopping',
  'shoppers stop': 'Shopping',
  lifestyle: 'Shopping',
  pantaloons: 'Shopping',
  westside: 'Shopping',
  zara: 'Shopping',
  'h&m': 'Shopping',
  croma: 'Shopping',
  'vijay sales': 'Shopping',
  'reliance digital': 'Shopping',
  'tata cliq': 'Shopping',
  'lime road': 'Shopping',
  firstcry: 'Shopping',
  shopclues: 'Shopping',
  decathlon: 'Shopping',
  nike: 'Shopping',
  adidas: 'Shopping',
  puma: 'Shopping',
  bata: 'Shopping',
  'clothing': 'Shopping',

  // Entertainment
  netflix: 'Entertainment',
  spotify: 'Entertainment',
  hotstar: 'Entertainment',
  disney: 'Entertainment',
  youtube: 'Entertainment',
  'amazon prime': 'Entertainment',
  'prime video': 'Entertainment',
  bookmyshow: 'Entertainment',
  inox: 'Entertainment',
  pvr: 'Entertainment',
  sonyliv: 'Entertainment',
  zee5: 'Entertainment',
  audible: 'Entertainment',
  gaana: 'Entertainment',
  wynk: 'Entertainment',
  jiosaavn: 'Entertainment',
  steam: 'Entertainment',
  playstation: 'Entertainment',
  xbox: 'Entertainment',
  'movie': 'Entertainment',
  cinema: 'Entertainment',
  gaming: 'Entertainment',
  aha: 'Entertainment',
  ulta: 'Entertainment',

  // Health
  apollo: 'Health & Medical',
  pharmeasy: 'Health & Medical',
  medplus: 'Health & Medical',
  hospital: 'Health & Medical',
  pharmacy: 'Health & Medical',
  netmeds: 'Health & Medical',
  '1mg': 'Health & Medical',
  'ck birla': 'Health & Medical',
  apollopharmacy: 'Health & Medical',
  'diagnostics': 'Health & Medical',
  clinic: 'Health & Medical',
  dentist: 'Health & Medical',
  doctor: 'Health & Medical',
  medical: 'Health & Medical',
  physio: 'Health & Medical',
  gym: 'Health & Medical',
  fitbit: 'Health & Medical',
  wellness: 'Health & Medical',

  // Fuel
  shell: 'Fuel',
  'indian oil': 'Fuel',
  iocl: 'Fuel',
  bpcl: 'Fuel',
  hpcl: 'Fuel',
  'hp petrol': 'Fuel',
  'hp': 'Fuel',
  'bharat petroleum': 'Fuel',
  petrol: 'Fuel',
  diesel: 'Fuel',
  'gas station': 'Fuel',
  fuel: 'Fuel',
  cng: 'Fuel',
  'indane': 'Fuel',

  // Bills & Utilities
  electricity: 'Bills & Utilities',
  'bengaluru electricity': 'Bills & Utilities',
  bescom: 'Bills & Utilities',
  tneb: 'Bills & Utilities',
  mseb: 'Bills & Utilities',
  'adani electricity': 'Bills & Utilities',
  'bs es': 'Bills & Utilities',
  water: 'Bills & Utilities',
  gas: 'Bills & Utilities',
  broadband: 'Bills & Utilities',
  jio: 'Bills & Utilities',
  airtel: 'Bills & Utilities',
  vi: 'Bills & Utilities',
  vodafone: 'Bills & Utilities',
  idea: 'Bills & Utilities',
  bsnl: 'Bills & Utilities',
  recharge: 'Bills & Utilities',
  'mobile bill': 'Bills & Utilities',
  'electricity bill': 'Bills & Utilities',
  dth: 'Bills & Utilities',
  'dish tv': 'Bills & Utilities',
  'tata sky': 'Bills & Utilities',
  'life insurance': 'Bills & Utilities',
  lic: 'Bills & Utilities',
  insurance: 'Bills & Utilities',
  'property tax': 'Bills & Utilities',
  // Grocery
  bigbasket: 'Grocery',
  blinkit: 'Grocery',
  zepto: 'Grocery',
  dmart: 'Grocery',
  'grofers': 'Grocery',
  more: 'Grocery',
  'reliance fresh': 'Grocery',
  'tata star': 'Grocery',
  'fresh': 'Grocery',
  spencers: 'Grocery',
  'star bazaar': 'Grocery',
  'big bazaar': 'Grocery',
  'grocery': 'Grocery',
  kirana: 'Grocery',
  sabji: 'Grocery',
  'easyday': 'Grocery',
  'local mart': 'Grocery',

  // Rent & Housing
  rent: 'Rent & Housing',
  'housing society': 'Rent & Housing',
  maintenance: 'Rent & Housing',
  nobroker: 'Rent & Housing',
  magicbricks: 'Rent & Housing',
  'landlord': 'Rent & Housing',
  'flat': 'Rent & Housing',
  housing: 'Rent & Housing',

  // EMI & Loans
  emi: 'EMI & Loans',
  loan: 'EMI & Loans',
  'home loan': 'EMI & Loans',
  'car loan': 'EMI & Loans',
  'personal loan': 'EMI & Loans',
  'bajaj finserv': 'EMI & Loans',
  'hdfc bank emi': 'EMI & Loans',
  'sbi emi': 'EMI & Loans',
  cred: 'EMI & Loans',
  slice: 'EMI & Loans',
  tapmad: 'EMI & Loans',
  paylater: 'EMI & Loans',

  // Investment
  'mutual fund': 'Investment',
  sip: 'Investment',
  zerodha: 'Investment',
  groww: 'Investment',
  kuvera: 'Investment',
  etmoney: 'Investment',
  upstox: 'Investment',
  indmoney: 'Investment',
  'icici direct': 'Investment',
  nse: 'Investment',
  bse: 'Investment',
  'share market': 'Investment',
  stocks: 'Investment',
  bond: 'Investment',
  'fd': 'Investment',
  ppf: 'Investment',
  demat: 'Investment',

  // Gifts & Donations
  gift: 'Gifts & Donations',
  donation: 'Gifts & Donations',
  ngo: 'Gifts & Donations',
  'charity': 'Gifts & Donations',
  giveindia: 'Gifts & Donations',
  fund: 'Gifts & Donations',
  crowdfunding: 'Gifts & Donations',
  raksha: 'Gifts & Donations',

  // Education
  books: 'Education',
  udemy: 'Education',
  coursera: 'Education',
  unacademy: 'Education',
  byjus: 'Education',
  vedantu: 'Education',
  college: 'Education',
  school: 'Education',
  tuition: 'Education',
  skillshare: 'Education',
  gfg: 'Education',
  'great learning': 'Education',
  upskilling: 'Education',
  'course': 'Education',
  ebooks: 'Education'
};

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'Food & Dining': ['food', 'coffee', 'pizza', 'burger', 'restaurant', 'lunch', 'dinner', 'swiggy', 'zomato'],
  'Travel & Transport': ['uber', 'ola', 'cab', 'taxi', 'metro', 'train', 'flight', 'bus', 'auto'],
  'Shopping': ['amazon', 'flipkart', 'myntra', 'shopping', 'shirt', 'dress'],
  'Entertainment': ['netflix', 'spotify', 'movie', 'game', 'concert', 'show'],
  'Health & Medical': ['hospital', 'doctor', 'pharmacy', 'medicine', 'gym'],
  'Fuel': ['petrol', 'diesel', 'fuel', 'gas', 'shell', 'cnp'],
  'Bills & Utilities': ['bill', 'electricity', 'water', 'recharge', 'internet', 'broadband', 'rent'],
  'Grocery': ['grocery', 'vegetables', 'milk', 'bigbasket', 'blinkit', 'dmart'],
  'EMI & Loans': ['emi', 'loan', 'interest'],
  'Investment': ['sip', 'mutual', 'stock', 'share', 'investment'],
  'Education': ['books', 'course', 'school', 'college', 'tuition'],
  'Rent & Housing': ['rent', 'maintenance', 'deposit'],
  'Gifts & Donations': ['gift', 'donation', 'charity'],
  'Other': []
};

export function detectCategory(merchant: string, categoryName?: string): string | undefined {
  const cleaned = merchant.toLowerCase().trim();
  if (!cleaned) return categoryName;
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    for (const k of keywords) {
      if (cleaned.includes(k)) return category;
    }
  }
  const key = cleaned.replace(/[^a-z0-9 ]/g, '').trim();
  const exact = MERCHANT_CATEGORY_MAP[key];
  if (exact) return exact;
  const words = key.split(' ');
  for (const w of words) {
    if (MERCHANT_CATEGORY_MAP[w]) return MERCHANT_CATEGORY_MAP[w];
  }
  return categoryName;
}
